[17기 박재현] 카카오톡 회원가입/로그인 뷰 작성
wecode-bootcamp-korea/17-2nd-CLASS404-backend pull request #3
Opened 2021-03-05 09:47 UTC by namujinju

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카카오톡 회원가입/로그인 뷰 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 카카오톡 회원가입 및 로그인 뷰 작성
- 유닛 테스트 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-03-05 11:20 UTC, ulfrid requested changes
확인 바랍니다~!

2021-03-05 11:20 UTC, devops-andrew commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
소셜 로그인의 경우, mocking & patching을 해주셔야 실제로 동작하지 않게 될텐데, 
현재 구현의 경우, Fixture도 유저는 생성되어 있지 않네요. 로그인 테스트인 만큼 회원가입은 고려하지 않게.
Mock Response 도 만들고 그에대한 Fixture도 생성하신뒤 patch를 통해 진짜로 카카오 API에 콣이 되지 않도록 해주셔야 합니다.

https://koreanblacklee.github.io/posts/python/Django/test2
참고하실만한 좋은 글을 공유드립니다.

2021-03-05 11:20 UTC, ulfrid commented on user/views.py
> +                user_info   = User.objects.get(social_login=user['id'])
유저가 이미 있다면 로그인 토큰을 발행해 주는게 아닌가요?

2021-03-05 11:20 UTC, ulfrid commented on user/views.py
> +                    user_type_id = 1
이렇게 하드 코딩 되면 무슨 상황인지 이해 할 수 없습니다. 이게 디폴트 라면, 상수값으로 선언해두고 주입해 주세요.

2021-03-05 12:24 UTC, namujinju commented on user/views.py
> +                    user_type_id = 1
네.변수로 상수값 지정하겠습니다.

2021-03-05 12:48 UTC, namujinju commented on user/views.py
> +                user_info   = User.objects.get(social_login=user['id'])
로그인과 회원가입을 조건문으로 나눠서 두 경우 모두 access token을 발행하게 조건문 밖에다 토큰 발행 부분을 만들었습니다.

2021-03-05 12:54 UTC, namujinju commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
unit test에서도 실제로 카카오 API가 동작하게 만들어야 하는 줄 알았습니다. 회원가입은 고려하지 않고 로그인만 테스트하게 수정하고 가짜 데이터도 만들어서 다시 해보겠습니다. 감사합니다.

2021-03-06 05:04 UTC, namujinju commented on user/tests.py
> +        self.assertEqual(response.status_code, 404)
mocking과 patching을 이용해 실제로 카카오 API를 콜하지 않게 수정했고,
tests.py에서 회원가입과 로그인을 모두 테스트하게 수정 완료했습니다.

2021-03-08 07:54 UTC, soheon-lee commented on user/views.py
> +            if User.objects.filter(social_login = str(user['id'])).exists():
```suggestion
            if User.objects.filter(social_login = str(user['id'])).exists():
```
여기 `str()`으로 형변환 하지 않으면 혹시 동작에 에러가 발생하나요?

2021-03-08 07:54 UTC, soheon-lee commented on user/views.py
> +
32번째에서 `else`문을 사용하지 않을 수 있도록 31번째 줄에서 바로 return을 할 수 있도록 해주세요 :)
그러면 else문 없이도 진행하실 수 있습니다.
꼭 필요하지 않은 else라면 사용하지 않으시는 것이 파이썬 다운 방법입니다.

2021-03-08 07:55 UTC, soheon-lee commented
unit test 고생하셨습니다 :)

2021-03-08 08:05 UTC, namujinju commented on user/views.py
> +            if User.objects.filter(social_login = str(user['id'])).exists():
User의 models.py를 작성할 때 당시 카톡에서 들어오는 id가 str인지 int인지 몰라서 일단 CharField로 작성해놨습니다. 결과적으로는 int가 들어왔고, 작업 편의를 위해 models.py에서 IntegerField로 바꾸는 대신 view에서 str으로 바꿔서 저장했습니다. models.py를 바꾸는 방향으로 팀원과 상의 후 결정하겠습니다.

2021-03-08 08:05 UTC, namujinju commented on user/views.py
> +
네 알겠습니다 수정하겠습니다!

2021-03-08 09:06 UTC, namujinju commented on user/views.py
> +
if에는 로그인, else에는 회원가입 후 로그인이니 로그인 부분이 중복되기 때문에 조건문 밖으로 빼냈습니다. 유저가 만들어지는 회원가입은 status code가 201이 더 맞기 때문에 회원가입 후 로그인인 경우에는 code=201로 따로 만들어보겠습니다.

2021-03-08 09:16 UTC, namujinju commented on user/views.py
> +
수정 완료했습니다!

2021-03-09 01:51 UTC, ulfrid commented
LGTM👍

2021-03-09 01:51 UTC, merged